# Run the below command when you edit .drone.yml
#   drone secure --repo haya14busa/reviewdog --in .drone.sec.yaml
#
build:
  test:
    image: golang
    commands:
      - go get -d -v -t ./...
      - go test -v ./...
      - (! gofmt -s -d . | grep '^') # exit 1 if any output given
  lint:
    image: golang
    environment:
      - REVIEWDOG_GITHUB_API_TOKEN=$$REVIEWDOG_GITHUB_API_TOKEN
    commands:
      - go get github.com/haya14busa/reviewdog/cmd/reviewdog
      - go get github.com/golang/lint/golint
      - go get honnef.co/go/unused/cmd/unused
      - go get honnef.co/go/simple/cmd/gosimple
      - go get github.com/kisielk/errcheck
      - reviewdog -ci=droneio
    when:
      event: pull_request

notify:
  gitter:
    webhook: "https://webhooks.gitter.im/e/8dfc2f32c464a65d6da2"
