# Run the below command when you edit .drone.yml
#   drone secure --repo haya14busa/reviewdog --in .drone.sec.yaml
#
build:
  test:
    image: golang:1.9
    commands:
      - go get -u github.com/golang/dep/...
      - dep ensure
      - go build -v $(go list ./... | grep -v "/vendor/")
      - go test -v -race $(go list ./... | grep -v "/vendor/")
      - (! gofmt -s -d *.go cmd diff project | grep '^')
  lint:
    image: golang
    environment:
      - REVIEWDOG_GITHUB_API_TOKEN=$$REVIEWDOG_GITHUB_API_TOKEN
    commands:
      - go install ./cmd/reviewdog
      - go vet ./... 2>&1 | reviewdog -reporter="github-pr-review" -ci=droneio
    when:
      event: pull_request

notify:
  gitter:
    webhook: "https://webhooks.gitter.im/e/8dfc2f32c464a65d6da2"
