# Open merge request automatically and run reviewdog against created MR.
stages:
  - openMr
  - reviewdog

# https://github.com/tmaier/gitlab-auto-merge-request
Open Merge Request:
  stage: openMr
  image: tmaier/gitlab-auto-merge-request:1
  before_script: []
  variables:
    GIT_STRATEGY: none
  script:
    - merge-request.sh

Reviewdog:
  stage: reviewdog
  image: golang:latest
  before_script:
    - export GO111MODULE=on
    # Set up $GOPATH and install reviewdog (Note that main repo is github.com)
    - ln -s /builds /go/src/github.com
    - cd /go/src/github.com/${CI_PROJECT_PATH}
    - go install ./cmd/reviewdog
    - ( cd linters && go get golang.org/x/lint/golint )
  script:
    - golint ./... | reviewdog -f=golint -name=golint-discussion -reporter=gitlab-mr-discussion
    - golint ./... | reviewdog -f=golint -name=golint-commit -reporter=gitlab-mr-commit
