language: go

go:
  - 1.7
  - tip

env:
  global:
    - secure: "CZlsRUQQjxx9XlMZT2GIpOFJiwGkvlF502UhvrlJuB+TCDJI0G5I1s5tkLVl2Sq+rG7jLwi//x97MbSAr/IW8xi4NSsVZiMIhmLMmLZxTSE1+pTOc7Iguerk5ilgxJTBb01cLKYIOyUpupD3O253cT0+SZ5nmugESYXp5Wm+R6CxtrcqtEKsHXKg4ajYyLdMWD2yYNimC0eHrmn8eFvGegoSQUUcGij0t0tSBebLNaLVJaEV38jD5eWHaMiOLVpG1mQNxFn2iEYcTLiEboa2RmL+YTwcE/AkZdFqvr+NxXEa+7vh7QlQaeiGcR5jyvNOehYdiQ/Ek5krwEUOjC1mZDHTgjZfTY8FNzo6fyi7swQxUup/hwYO8gWhgZhDiggYNP5QQmfxljVHotPUX6C90YRCLKVCi55nw/UsVxtkeRG12MLQ68gax3Osh7P2UwsdexwveJG8tkUrFIbtdwNqzyI8M9TdaTlzHk6c5a/MQM/cL68vd2O5El6dldaML76XqV3ZIuSV9gB99lipriBC2TcMNmY9g4P76bFnsR3s3QX7K7oYugJw3zF6PjXAkUt+2DsWWUl7x5FKxuTBKYJkdgp0kDzwFbjE1fm3U8rzqDxnM25NVqOt5dUkmQcclIw39zlPkwY3C94x1TycSmgt/shL1PeZUbpSZJUPcmisOCw="

before_script:
  - echo $TRAVIS
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_PULL_REQUEST_SHA
  - echo $TRAVIS_REPO_SLUG
  - echo $TRAVIS_SECURE_ENV_VARS

install:
  - go get -d -v -t ./...
  - go get github.com/mattn/goveralls
  - go get github.com/golang/lint/golint

script:
  - go test -v -race ./...
  - goveralls -service=travis-ci
  # - go vet ./... ref: circle.yml
  # - unused ./... ref: .drone.yml
  - go install ./cmd/watchdogs
  - >-
    golint ./... | watchdogs -efm="%f:%l:%c: %m" -ci=travis
