language: go

go:
  - 1.7
  - tip

env:
  global:
    - secure: "RzVf38xAXHzHLm7bb2Z5xoj3DgEhPmZcsfiGApwKmLehA2p1vyGovINR0oZ3KDKSmJVDz+Bqhj8fWBD9fudtcKeZQaE11K9qbE6NAHrJbOJOjmtYQB6oXaDeNeNXBKClr5kvGdvP8Mahddff4FEJLt8alLEvwnP0FfobCcs7EoANl3E+N5wmXwI7neVojlPLTdbGjO6HA0+gqcvTZdXQUwYrmrmOKDM9pQwVQ2MpGaDlehsZOd0iSuVPs5VOCpYSopTROVdLH+N5R7+atjs+wf2qhA8608LkeD8yWhYQQhQ03muzat0jQALpmOMO8qu4pD9a7aFLCgvUbUvC6Z4gJBFdvgB3xJxAe+dwuql9yiTq9/SH7EMlxiS1AiP0daRnakrJ2N82mKRUzWytf+4OeQydn6zK6GcZH4onYALyXZ+liur3tDsRQ5EDPqV1LLD1J9xPVC2mBH+NyfY7Ymr186bTFWrHVJ43K209qZX1Qg5AF2nEfV7EkAv/hGGDoctm5JEoegu0t5wZdU1KPUIjGLMDUD3Z/nMPkWTVfoYVTDdfTUrwqzixYDO61CgDy5zbz/FsYVWB5JVCK4mT3XcK5n2YY3KXRlIkxgfFA6XDaXEc3OBGvdJotvTG23ZWFV/K4KSGYqMagITDnXzY/pEYaBK1UiLH/AMIYDlS6wcfE5w="

before_script:
  - echo $TRAVIS
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_PULL_REQUEST_SHA
  - echo $TRAVIS_REPO_SLUG
  - echo $TRAVIS_SECURE_ENV_VARS

install:
  - go get -d -v -t ./...
  - go get github.com/mattn/goveralls
  - go get github.com/golang/lint/golint

script:
  - go test -v -race ./...
  - goveralls -service=travis-ci
  # - go vet ./... ref: circle.yml
  # - unused ./... ref: .drone.yml
  - go install ./cmd/reviewdog
  - >-
    golint ./... | reviewdog -f=golint -ci=travis
