# reviewdog app config: https://github.com/settings/apps/reviewdog

# https://cloud.google.com/appengine/docs/standard/go/config/appref
runtime: go
api_version: go1.9

# https://cloud.google.com/appengine/docs/standard/go/warmup-requests/configuring
inbound_services:
- warmup

includes:
- handlers.yaml
- secret/secret.yaml # set GITHUB_WEBHOOK_SECRET env var
