# https://cloud.google.com/appengine/docs/standard/go/config/appref
runtime: go
api_version: go1.9

handlers:
- url: /secret/*
  secure: always
  script: _go_app

- url: /.*
  script: _go_app

includes:
- secret/secret.yaml # set GITHUB_WEBHOOK_SECRET env var
